resampling_geneList<- function(geneList.true,
                               perm.n=5000){
  if (perm.n>10000){stop('10k perm.id is supported')} 
  geneList.null= replicate(n = perm.n+100, sample(geneList.true,size=dim(geneList.true)[1],replace=F), simplify = T)
  geneList.null=geneList.null[,!duplicated(t(geneList.null))] # remove dupliated column
  geneList.null=geneList.null[,c(1:perm.n)]
  rownames(geneList.null)=rownames(geneList.true)
  colnames(geneList.null)=paste0('null_',c(1:perm.n))
  attr(geneList.null,'is_fisherz')=attr(geneList.true,'is_fisherz')
  attr(geneList.null,'n.region')=attr(geneList.true,'n.region')
  return(geneList.null)
}


# resampling_geneList_matching_coexp <- function(
#                                    geneList.true,
#                                    gs,
#                                    coexp_matrix, #coexp_matrix=cor(gene_data)
#                                    perm.n=5000,...){

# if (!is.matrix(geneList.true)){
#   stop('geneList.true should be a m x 1 vector/matrix. Pls include drop=F when subsetting')
# }else{
#     if (dim(geneList.true)[2]>1){
#     stop('geneList.true should be a m x 1 vector/matrix.')}
# }

# # find gene sets with similar co-expression
# sampled_gs=sample_gs_with_coexp(coexp_matrix=coexp_matrix,
#                                 gs=gs,
#                                 n_target=perm.n,...)

# # swap their value and create the null geneList
# geneList.null=swap_geneList(geneList.true=geneList.true,
#                             gs=gs,
#                             sampled_gs = sampled_gs)
# return(geneList.null)
# }

sample_geneSetList_with_constrains <- function(geneSetList,
                                               constrain=c('match_coexp','gene_subset'),
                                               coexp_matrix=NULL, #coexp_matrix=cor(gene_data)
                                               gene_subset=NULL){
 constrain=match.arg(constrain)
 if (constrain=='match_coexp'){
    if (is.null(coexp_matrix)){
      stop('coexp_matrix is required for match_coexp')
    }
  sampled_geneSetList=lapply(geneSetList, sample_gs_matching_coexp, coexp_matrix=coexp_matrix)
  }else if (constrain=='gene_subset'){
    if (is.null(gene_subset)){
      stop('gene_subset is required for gene_subset')
    }
    sampled_geneSetList=lapply(geneSetList, sample_gs_within_subset, gene_subset=gene_subset)
  return(sampled_geneSetList)}  
}
 


sample_gs_matching_coexp <- function(gs,
                                  coexp_matrix,#coexp_matrix=cor(gene_data)
                                  tol=0.01,
                                  max_iter=1000000,
                                  n_target=5000){
# Function to sample gene sets with similar co-expression
# Input:
#   gene_data: gene expression data
#   gs: gene set of interest
#   tol: tolerance of difference between target co-expression and sampled co-expression
#   max_iter: maximum number of iterations
#   n_target: number of gene sets to be sampled
# Output:
#   sampled_gs: a list of sampled gene sets with similar co-expression

# caculate co-expression of gs

gs_coexp_matrix <- coexp_matrix[gs, gs]
gs_coexp_lower <- gs_coexp_matrix[lower.tri(gs_coexp_matrix)]
target_coexp <- mean(gs_coexp_lower)

# sample gs with similar co-expression
sampled_gs <- list()

for (i in 1:max_iter) {
  
  sampled_genes <- sample(colnames(coexp_matrix), length(gs), replace = F)
  sampled_coexp_matrix <- coexp_matrix[sampled_genes, sampled_genes]
  sampled_coexp_lower <- sampled_coexp_matrix[lower.tri(sampled_coexp_matrix)]
  sampled_coexp.avg <- mean(sampled_coexp_lower)
  
  if (abs(sampled_coexp.avg  - target_coexp) < tol) {
    sampled_gs[[length(sampled_gs) + 1]] <- sampled_genes
  }
  
  #remove duplciated gs (element)
  sampled_gs <- unique(sampled_gs)

  # break the for loop if n_target reached
    if (length(sampled_gs)==n_target){
    break
  }
  }

  # if n_target not reached, print warning
  if (length(sampled_gs) < n_target) {
    warning('n_target not reached, consider increasing max_iter or decreasing tol')
  }
return(sampled_gs)
}


sample_gs_within_subset <- function(gs,
                                   gene_subset, # small subset of genes with greater rdonor
                                   perm.n=5000){

# find gene sets from gene_subset
sampled_gs= lapply(1:perm.n+100,function(i){
  sample(gene_subset,size=length(gs),replace=F)
})
sampled_gs <- unique(sampled_gs)
sampled_gs <- sampled_gs[1:perm.n]
return(sampled_gs)
}



swap_geneList <- function(geneList.true,
                          orig_gs,sampled_gs){
# Helper function to swap the orginal value of gs with sampled_gs
# In this way, the output geneList.null is in the same format as generated by other approach
if (!is.matrix(geneList.true)){
  stop('geneList.true should be a m x 1 vector/matrix. Pls include drop=F when subsetting')
}else{
    if (dim(geneList.true)[2]>1){
    stop('geneList.true should be a m x 1 vector/matrix.')}
}
gnames=rownames(geneList.true)
origVals=as.numeric(geneList.true[gnames %in% orig_gs,]) # geneList.true[gs,] will keep the order of gs; use geneList.true[gnames %in% gs,] to force the same order
null_list=lapply(sampled_gs,function(gs_i){
  tmp_null=geneList.true
  swapVals=as.numeric(geneList.true[gnames %in% gs_i,])
  tmp_null[gnames %in% gs_i,]=origVals
  tmp_null[gnames %in% orig_gs,]=swapVals
  return(tmp_null)
})
null_geneList=do.call(cbind,null_list)
colnames(null_geneList)=paste0('null_',1:ncol(null_geneList))
attr(null_geneList,'is_fisherz')=attr(geneList.true,'is_fisherz')
attr(null_geneList,'n.region')=attr(geneList.true,'n.region')

return(null_geneList)
}

# ====================toy data for swap function =====================================
# set.seed(123)  # for reproducibility
# # Generate geneList.true
# num_genes <- 100  # total number of genes
# geneList.true <- matrix(1:100, ncol = 1)
# rownames(geneList.true) <- paste0("Gene", 1:num_genes)
# # Generate gs (gene set)
# num_gs <- 10  # size of gs
# gs <- sample(rownames(geneList.true), num_gs)
# # Generate sampled_gs (another gene set with the same size as gs)
# sampled_gs <- replicate(10, sample(rownames(geneList.true), num_gs), simplify = FALSE)
# result <- swap_geneList(geneList.true, gs, sampled_gs)